export const POKE_REQUEST = "POKE_REQUEST"
export const POKE_SUCCESS = "POKE_SUCCESS"
export const POKE_FAILURE = "POKE_FAILURE"

export const POKE_STATUS_REQUEST = "POKE_STATUS_REQUEST"
export const POKE_STATUS_SUCCESS = "POKE_STATUS_SUCCESS"
export const POKE_STATUS_FAILURE = "POKE_STATUS_FAILURE"